### ISSUE TITLE
Progressen vises ikke

### ISSUE THREAD

**Issue by piravp** [Hellowlol/nrk_api#10]
Filene lastes ned, men det vises ikke progress underveis. 
Selv etter at filene har lastet ferdig står den bare sånn:
![image](https://cloud.githubusercontent.com/assets/18312063/24988564/0f4ec84c-2007-11e7-9709-122dd0bee548.png)
`Ctrl+C` vil heller ikke avslutte prosessen, så jeg må inn i Task Manager og avslutte prosessen manuelt.

**Python:** 3.4.4
**ffmpeg:** ffmpeg version N-83622-gdcd3418 
**OS:** Windows 10 (64 bit)

Ellers ros for et intuitivt CLI!

**Comment by Hellowlol** [comment]
Hei!

Takk for tilbakemeldingen! Progressen virker men det er etter filene er nedlastet

Feks hvis skal laste ned nobel:
````py nrkdl.py -s nobel ````

Uten noen andre parametere vil 4 filer bli lastet ned, de vil være ferdige ca samtidig så progressen hopper fra 0%  til 60%

Hvis du vil laste ned en og en kan du legge til ``-w 1 -c 1`` (progress vil vises en etter en da, men nedlastningen tar lengre tid..)

nrkdl trenger litt tlc, jeg skal få fikset travis og ctrl-c :)

**Comment by piravp** [comment]
Hei igjen!

Testet dette på nytt nå. Med litt tålmodighet hopper den nå fra 0 til 100 % når den er ferdig. 
Ser fram til neste oppdatering 👍

**Comment by Hellowlol** [comment]
Jeg har begynt på en ny progress bar. Hver nedlastning får en egen progess bar samt en som viser alle. Jeg håper jeg kan få det ferdig i helga
