### ISSUE TITLE
Feil ved bruk av dockerfile

### ISSUE THREAD

**Issue by espen4001** [Hellowlol/nrk_api#13]
Prøver å generere et image fra dockerfile, men ender etterhvert opp med følgende feilmelding:

> Cloning into 'nrkdl'...
> Ignoring colorama: markers 'sys_platform == "windows"' don't match your environment
> Collecting aiohttp>=2.1.0 (from -r requirements.txt (line 1))  Downloading https://files.pythonhosted.org/packages/2e/e6/9175733f42cec4f2cd6834564517f2f6260e27dab5edb75afdaa66f101bb/aiohttp-2.3.1.tar.gz (1.1MB)
> aiohttp requires Python '>=3.4.2' but the running Python is 2.7.15
> You are using pip version 9.0.0, however version 20.0.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> The command '/bin/sh -c apk update     && apk add python py-pip git ffmpeg     && git clone https://github.com/Hellowlol/nrkdl.git && cd nrkdl     && pip install -r requirements.txt' returned a non-zero code: 1

Kjører docker på Ubuntu 19.10.
Ser ut som det er noe versjoner av de ulike pakkene som ikke passer sammen?

Update: Endret dockerfile til å bruker python3.7.7-alpine som utgangspunkt, men da kom det mye mer feil.

**Comment by Hellowlol** [comment]
Jeg har ikke brukt denne pakka på lenge men jeg tror ikke den virker lengre pga jeg ikke hadde låst noen deps som er blitt endret. Jeg skal se på det.

**Comment by espen4001** [comment]
Forsøkte å kjøre alle kommandoen fra dockerfile og requirements-filen manuelt i containeren, og det er installasjon av aiohttp som feiler. Sier den krever Python 3.4.5 eller høyere. Men oppgraderes Python til siste versjon i containeren, så feiler den på mye annet. Men kanskje en plass å begynne er å se på hvorfor aiohttp-installasjonen ikke går? Kanskje en annen versjon av den kan benyttes?
