### ISSUE TITLE
seriesID er tom

### ISSUE THREAD

**Issue by marhoy** [Hellowlol/nrk_api#5]
Hei,

Jeg får følgende feilmelding under MacOS med Python 3.5.2:

marhoy@MBP: ~/GitHub/nrkdl
$ python nrkdl.py -s pinnemann
  0: Pinnemann
Traceback (most recent call last):
  File "nrkdl.py", line 1085, in <module>
    main()
  File "nrkdl.py", line 1072, in main
    nrk._console(p.search)
  File "nrkdl.py", line 505, in _console
    to_download.append(_build(sr['hit']))
  File "nrkdl.py", line 125, in _build
    if hit_type == 'serie' or item.get('seriesId', '').strip():
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by Hellowlol** [comment]
Mulig de har endret noe pga du skulle aldri ha fått den feilmeldingen. Enten skal det ha en seriesId eller ikke. Ser ut som det er blitt lagt inn selvom det er et program. 

I mellomtiden kan du laste det ned via url:
python nrkdl.py -u https://tv.nrk.no/program/MSUI21007014/pinnemann

**Comment by Hellowlol** [comment]
Både -u og -s skal virke nå.

**Comment by marhoy** [comment]
Hei,

Tusen takk, virker nå!
Jeg har brukt nrkopptak tidligere, og oppdaget nrkdl i går.
Muligheten til å browse, søke og laste ned med slice-kommandoer er helt overlegen :)

**Comment by Hellowlol** [comment]
Flott! Jeg bruke vx_nrk før, flott program men det ble for mye jobb å finne det jeg skulle ha dra over en og en link.
