### ISSUE TITLE
Trouble downloading certain content

### ISSUE THREAD

**Issue by ty1981567** [Hellowlol/nrk_api#6]
I am having issues downloading certain content,  For example :
$ python nrkdl.py -e utf8 -s 'skomakergata' -st 
  9: Da Capo!
  8: Da Capo! Med Sigmund Groven
  7: Syngsalabim! 2:4
  6: SKAI-TV 1:6
  5: Henki Kolstad
  4: Kanal 1 13.12.1985
  3: Barnas øyeblikk
  2: Distriktsnyheter Østnytt 19.12.2011
  1: Selskapet 1:12
  0: Jul i Skomakergata

Select a number or use slice notation
0

 23: Jul i Skomakergata S01E01
 22: Jul i Skomakergata S01E02
 21: Jul i Skomakergata S01E03
 20: Jul i Skomakergata S01E04
 19: Jul i Skomakergata S01E05
 18: Jul i Skomakergata S01E06
 17: Jul i Skomakergata S01E07
 16: Jul i Skomakergata S01E08
 15: Jul i Skomakergata S01E09
 14: Jul i Skomakergata S01E10
 13: Jul i Skomakergata S01E11
 12: Jul i Skomakergata S01E12
 11: Jul i Skomakergata S01E13
 10: Jul i Skomakergata S01E14
  9: Jul i Skomakergata S01E15
  8: Jul i Skomakergata S01E16
  7: Jul i Skomakergata S01E17
  6: Jul i Skomakergata S01E18
  5: Jul i Skomakergata S01E19
  4: Jul i Skomakergata S01E20
  3: Jul i Skomakergata S01E21
  2: Jul i Skomakergata S01E22
  1: Jul i Skomakergata S01E23
  0: Jul i Skomakergata S01E24

Select a number or use slice notation
::
Traceback (most recent call last):
  File "nrkdl.py", line 1096, in <module>
    main()
  File "nrkdl.py", line 1083, in main
    nrk._console(p.search)
  File "nrkdl.py", line 523, in _console
    d.subtitle()
  File "nrkdl.py", line 693, in subtitle
    return Subtitle().get_subtitles(self.id, name=self.name, file_name=self.file_name)
  File "nrkdl.py", line 907, in get_subtitles
    content = cls._ttml_to_srt(html)
  File "nrkdl.py", line 995, in _ttml_to_srt
    output.write(text)
TypeError: unicode argument expected, got 'str'

**Comment by Hellowlol** [comment]
What Python version and is?

**Comment by ty1981567** [comment]
Python version is 2.7.12

**Comment by Hellowlol** [comment]
Os and locale? If you can live without subtitle the download should work. Thanks for the bug report

**Comment by ty1981567** [comment]
Linux,  locale:

$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nb_NO.UTF-8
LC_TIME=nb_NO.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nb_NO.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nb_NO.UTF-8
LC_NAME=nb_NO.UTF-8
LC_ADDRESS=nb_NO.UTF-8
LC_TELEPHONE=nb_NO.UTF-8
LC_MEASUREMENT=nb_NO.UTF-8
LC_IDENTIFICATION=nb_NO.UTF-8
LC_ALL=

And yes it seems to work if I don't use  - st

**Comment by Hellowlol** [comment]
Sweet. I was planning adding support for proxys so we can get around nrks geo block anyway. I'll fix this at the same time.

**Comment by Hellowlol** [comment]
Can you check if it works now?

**Comment by ty1981567** [comment]
Yes,  tested and working. 

Thanks
